-- The schema Routarr 0.1.0 creates, in one migration.
--
-- It replaces the twenty files that built it one change at a time. Squashing
-- is safe here and nowhere later: 0.1.0 had not been installed by anyone when
-- this was written, so there is no database carrying the old names in
-- `_migrations` and no backup whose manifest records one. After a release has
-- been used, the twenty would have had to stay.
--
-- Generated by applying those twenty to an empty database and dumping the
-- result, never by concatenating them: an `ALTER TABLE` in the tenth file is
-- invisible to a reader assembling the first by hand.
--
-- What the squash also removed: a migration that repaired an installation
-- whose two statements of the default category disagreed. That state can only
-- arise from the schema as it stood midway through the twenty, so from here it
-- is unreachable by construction, and the test that reached it went with it.


CREATE TABLE instances (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    instance_type TEXT NOT NULL CHECK(instance_type IN ('radarr', 'sonarr')),
    base_url TEXT NOT NULL,
    api_key TEXT NOT NULL,
    enabled INTEGER NOT NULL DEFAULT 1,
    sync_interval_minutes INTEGER NOT NULL DEFAULT 15,
    last_sync_at TEXT,
    last_sync_status TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
, webhook_token TEXT, last_sync_attempt_at TEXT);

CREATE TABLE categories (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE media (
    id TEXT PRIMARY KEY,
    instance_id TEXT NOT NULL REFERENCES instances(id) ON DELETE CASCADE,
    arr_id INTEGER NOT NULL,
    media_type TEXT NOT NULL CHECK(media_type IN ('movie', 'series')),
    title TEXT NOT NULL,
    sort_title TEXT,
    year INTEGER,
    tmdb_id INTEGER,
    tvdb_id INTEGER,
    imdb_id TEXT,
    current_path TEXT,
    current_root_folder TEXT,
    monitored INTEGER NOT NULL DEFAULT 1,
    has_files INTEGER NOT NULL DEFAULT 0,
    status TEXT,
    added_at TEXT,
    last_synced_at TEXT, series_type TEXT, size_on_disk INTEGER, season_count INTEGER, tags TEXT, genres TEXT, original_language TEXT, certification TEXT, moved_at TEXT,
    UNIQUE(instance_id, arr_id)
);

CREATE TABLE rules (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    priority INTEGER NOT NULL DEFAULT 100,
    enabled INTEGER NOT NULL DEFAULT 1,
    media_type TEXT NOT NULL CHECK(media_type IN ('movie', 'series', 'both')),
    conditions TEXT NOT NULL DEFAULT '[]',
    target_category TEXT NOT NULL,
    instance_ids TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
, match_mode TEXT NOT NULL DEFAULT 'all', exclusions TEXT NOT NULL DEFAULT '[]');

CREATE TABLE overrides (
    id TEXT PRIMARY KEY,
    media_id TEXT NOT NULL REFERENCES media(id) ON DELETE CASCADE,
    target_category TEXT NOT NULL,
    reason TEXT,
    locked INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE(media_id)
);

CREATE TABLE decisions (
    id TEXT PRIMARY KEY,
    media_id TEXT NOT NULL,
    media_title TEXT NOT NULL,
    media_type TEXT NOT NULL,
    instance_id TEXT NOT NULL,
    instance_name TEXT,
    current_root_folder TEXT,
    target_root_folder TEXT,
    target_category TEXT NOT NULL,
    matched_rule_id TEXT,
    matched_rule_name TEXT,
    is_override INTEGER NOT NULL DEFAULT 0,
    reasons TEXT NOT NULL DEFAULT '[]',
    alternatives TEXT NOT NULL DEFAULT '[]',
    action TEXT NOT NULL CHECK(action IN ('none', 'move', 'skip')),
    status TEXT NOT NULL CHECK(status IN ('pending', 'approved', 'applied', 'failed', 'skipped')),
    error_message TEXT,
    decided_at TEXT NOT NULL DEFAULT (datetime('now')),
    applied_at TEXT
, confidence REAL NOT NULL DEFAULT 0, superseded INTEGER NOT NULL DEFAULT 0, simulation_id TEXT, reverted_at TEXT, actor TEXT, subject TEXT);

CREATE TABLE settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE execution_logs (
    id TEXT PRIMARY KEY,
    decision_id TEXT REFERENCES decisions(id),
    action TEXT NOT NULL,
    details TEXT,
    success INTEGER NOT NULL,
    error_message TEXT,
    executed_at TEXT NOT NULL DEFAULT (datetime('now'))
, instance_id TEXT, media_id TEXT, media_title TEXT, actor TEXT, subject TEXT);

CREATE INDEX idx_media_instance ON media(instance_id);

CREATE INDEX idx_media_tmdb ON media(tmdb_id);

CREATE INDEX idx_media_type ON media(media_type);

CREATE INDEX idx_decisions_media ON decisions(media_id);

CREATE INDEX idx_decisions_status ON decisions(status);

CREATE INDEX idx_decisions_decided_at ON decisions(decided_at);

CREATE INDEX idx_rules_priority ON rules(priority);

CREATE INDEX idx_execution_logs_decision ON execution_logs(decision_id);

CREATE TABLE jobs (
    id TEXT PRIMARY KEY,
    kind TEXT NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('queued', 'running', 'success', 'failed', 'cancelled')),
    trigger TEXT NOT NULL DEFAULT 'manual',
    instance_id TEXT,
    detail TEXT,
    progress_current INTEGER NOT NULL DEFAULT 0,
    progress_total INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    started_at TEXT NOT NULL DEFAULT (datetime('now')),
    finished_at TEXT
);

CREATE INDEX idx_jobs_started_at ON jobs(started_at DESC);

CREATE INDEX idx_jobs_status ON jobs(status);

CREATE INDEX idx_decisions_media_status ON decisions(media_id, status, superseded);

CREATE INDEX idx_decisions_simulation ON decisions(simulation_id);

CREATE INDEX idx_execution_logs_executed_at ON execution_logs(executed_at DESC);

CREATE INDEX idx_overrides_media ON overrides(media_id);

CREATE TABLE arr_tags (
    instance_id TEXT NOT NULL REFERENCES instances(id) ON DELETE CASCADE,
    arr_id INTEGER NOT NULL,
    label TEXT NOT NULL,
    PRIMARY KEY (instance_id, arr_id)
);

CREATE INDEX idx_media_series_type ON media(series_type);

CREATE TABLE metadata_cache (
    -- `tmdb`, and tomorrow `anilist` or `omdb`. Not an enum: a provider is
    -- added in code, and a CHECK would turn that into a migration.
    source TEXT NOT NULL,
    -- The id in that provider's namespace, as text — TMDb numbers them, OMDb
    -- keys on `tt…`.
    external_id TEXT NOT NULL,
    media_type TEXT NOT NULL CHECK(media_type IN ('movie', 'series')),
    genres TEXT NOT NULL DEFAULT '[]',
    keywords TEXT NOT NULL DEFAULT '[]',
    original_language TEXT,
    origin_countries TEXT DEFAULT '[]',
    certification TEXT,
    status TEXT,
    overview TEXT,
    poster_path TEXT,
    cached_at TEXT NOT NULL DEFAULT (datetime('now')),
    expires_at TEXT NOT NULL,
    PRIMARY KEY(source, external_id, media_type)
);

CREATE INDEX idx_metadata_cache_expires ON metadata_cache(expires_at);

CREATE TABLE source_identifiers (
    source TEXT NOT NULL,
    media_type TEXT NOT NULL CHECK(media_type IN ('movie', 'series')),
    -- The library's own identity for the item, namespaced: `tmdb:8392`,
    -- `tvdb:76885`, `imdb:tt0096283`, or a normalised title and year when the
    -- item has no external id at all. Shared by every instance holding the same
    -- item, so a film present in two Radarrs is resolved once.
    local_key TEXT NOT NULL,
    -- NULL means "searched, found nothing".
    external_id TEXT,
    resolved_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY(source, media_type, local_key)
);

CREATE INDEX idx_source_identifiers_resolved ON source_identifiers(resolved_at);

CREATE TABLE rule_tests (
    id TEXT PRIMARY KEY,
    -- What the case claims, in the author's words.
    name TEXT NOT NULL,
    media_type TEXT NOT NULL CHECK(media_type IN ('movie', 'series')),
    -- Serialised `Media`, and the merged metadata if any was known.
    media_json TEXT NOT NULL,
    metadata_json TEXT,
    evaluated_at TEXT NOT NULL,
    expected_category TEXT NOT NULL,
    -- Where it came from, for the "pin this decision" button. Free text and
    -- never joined on: the media row it names may be gone by the next sync.
    source_media_title TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_rule_tests_name ON rule_tests(name);

CREATE INDEX idx_media_imdb ON media(imdb_id);

CREATE INDEX idx_media_tvdb ON media(tvdb_id);

CREATE INDEX idx_metadata_cache_external ON metadata_cache(external_id, media_type);

CREATE TABLE users (
    id TEXT PRIMARY KEY,
    username TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE sessions (
    id TEXT PRIMARY KEY,
    -- Who the session belongs to: a username today, an OIDC subject later.
    subject TEXT NOT NULL,
    -- Which mode opened it, so a mode change does not leave live sessions it
    -- would never have granted.
    source TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    expires_at TEXT NOT NULL,
    last_used_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_sessions_expires ON sessions(expires_at);

CREATE TABLE oidc_flows (
    state TEXT PRIMARY KEY,
    nonce TEXT NOT NULL,
    verifier TEXT NOT NULL,
    expires_at TEXT NOT NULL
);

CREATE INDEX idx_oidc_flows_expires ON oidc_flows(expires_at);

CREATE TABLE probe_results (
    subject TEXT PRIMARY KEY,
    reachable INTEGER NOT NULL,
    -- The phrase the probe came back with, since the message names it. Already
    -- what the diagnostics table shows, so it exposes nothing new.
    detail TEXT,
    checked_at TEXT NOT NULL
);

CREATE TABLE "root_folders" (
    id TEXT PRIMARY KEY,
    instance_id TEXT NOT NULL REFERENCES instances(id) ON DELETE CASCADE,
    arr_id INTEGER,
    path TEXT NOT NULL,
    free_space INTEGER,
    accessible INTEGER NOT NULL DEFAULT 1,
    category TEXT,
    last_synced_at TEXT,
    last_accessible_at TEXT,
    -- 'arr' for a folder the instance reports, 'declared' for one typed here.
    -- The sync's orphan cleanup reads it: without it the first pass after a
    -- declaration would delete the row and the category mapped onto it.
    origin TEXT NOT NULL DEFAULT 'arr',
    UNIQUE(instance_id, arr_id)
);

CREATE INDEX idx_source_identifiers_external
    ON source_identifiers(source, media_type, external_id);

CREATE INDEX idx_root_folders_instance ON root_folders(instance_id);

CREATE INDEX idx_root_folders_category ON root_folders(instance_id, category);


-- The rows a fresh installation starts with. `default_category` is the one the
-- engine falls back to and the one the delete guard protects, which is why the
-- category it names has to exist from the first boot.

INSERT INTO categories (id, name, description, display_order, created_at) VALUES ('cat-standard', 'standard', 'Default category for unclassified media', 0, '2026-09-22 20:36:21');

INSERT INTO settings (key, value, updated_at) VALUES ('default_category', 'standard', '2026-09-22 20:36:21');

INSERT INTO settings (key, value, updated_at) VALUES ('global_dry_run', 'true', '2026-09-22 20:36:21');

INSERT INTO settings (key, value, updated_at) VALUES ('batch_limit', '50', '2026-09-22 20:36:21');

INSERT INTO settings (key, value, updated_at) VALUES ('metadata_cache_ttl_days', '7', '2026-09-22 20:36:21');

INSERT INTO settings (key, value, updated_at) VALUES ('auto_sync_enabled', 'true', '2026-09-22 20:36:21');

INSERT INTO settings (key, value, updated_at) VALUES ('decision_retention_days', '30', '2026-09-22 20:36:21');

INSERT INTO settings (key, value, updated_at) VALUES ('log_retention_days', '90', '2026-09-22 20:36:21');

INSERT INTO settings (key, value, updated_at) VALUES ('confirmation_threshold', '10', '2026-09-22 20:36:21');

INSERT INTO settings (key, value, updated_at) VALUES ('refresh_after_move', 'true', '2026-09-22 20:36:21');

INSERT INTO settings (key, value, updated_at) VALUES ('move_files_default', 'false', '2026-09-22 20:36:21');

INSERT INTO settings (key, value, updated_at) VALUES ('scheduler_interval_minutes', '15', '2026-09-22 20:36:21');

INSERT INTO settings (key, value, updated_at) VALUES ('metadata_providers', 'arr,tmdb', '2026-09-22 20:36:21');

INSERT INTO settings (key, value, updated_at) VALUES ('ui_language', 'en', '2026-09-22 20:36:21');
