-- When Routarr itself last moved this item, and why the sync must know.
--
-- `apply` and `sync:{instance}` are different job locks, so an application and
-- a synchronisation of the same instance can run at once — and both write
-- `media.current_root_folder`. The losing interleaving is:
--
--   1. the sync reads the Arr and receives the *old* path;
--   2. an apply moves the item and rewrites the local row to the new path;
--   3. the sync's transaction commits and puts the old path back.
--
-- Nothing is lost, but the next simulation reproposes a move that has already
-- happened — which is exactly what the executor's rewrite exists to prevent.
--
-- The fix is not a lock: excluding the two would mean refusing an apply for the
-- whole duration of a sync, network read included, on a schedule nobody asked
-- for. It is a read timestamp. The sync captures the instant *before* it starts
-- reading, and overwrites the path columns only when that instant is later than
-- the last move — i.e. only when its data cannot predate the move.
--
-- Second granularity is the same as every other timestamp here. A tie resolves
-- in favour of the applied value, which is the safe direction: if the tie is
-- spurious the two agree anyway, since the apply is what told the Arr.
ALTER TABLE media ADD COLUMN moved_at TEXT;
