#!/usr/bin/env bash
# Bound the caches that otherwise only grow: superseded VS Code server builds,
# the extension download caches, and the Rust build tree.
#
# The rule is not "delete caches". One that regenerates for free is cleared; one
# that costs compute is given a ceiling; one that costs a download is left
# alone. Four categories, and nothing here blurs them:
#
#   ramdisk        nothing preserved. Only kept from *filling*, since a full
#                  tmpfs fails a build with ENOSPC.
#   stale on disk  `backend/target` once CARGO_TARGET_DIR points elsewhere.
#                  Removed on evidence, never on assumption.
#   worth keeping  /cargo, /playwright, node_modules, credentials. Untouched.
#   sources        the checkout and .git. Untouched; the root check below is
#                  what stops a wrong guess reaching them.
#
# Armed by `postStartCommand` and `postAttachCommand` with `--daemon`. Safe to
# run by hand; `--status` reports without changing anything.
set -euo pipefail

# Checked against a file only this repository has: a root resolved wrongly would
# match no directories and report a clean pass having done nothing.
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
if [ ! -f "$root/backend/Cargo.toml" ]; then
  echo "prune: $root does not look like the Routarr checkout — skipping the Rust tree" >&2
  root=""
fi
RAMDISK="${ROUTARR_RAMDISK:-/ramdisk}"

SERVER_BUILDS=/vscode/vscode-server/bin/linux-x64
# Builds kept besides the one in use. Each is ~700 MB and buys one step back:
# a downgrade finds its build here instead of re-fetching it.
KEEP_SERVER_BUILDS=2

note() { echo "prune: $*"; }
size_kb() { du -sk "$1" 2>/dev/null | cut -f1 || echo 0; }

# Which filesystem a path actually sits on. `--target` resolves to the mount
# holding it, so this answers for a directory that does not exist yet as well.
fs_of() { findmnt -no FSTYPE --target "$1" 2>/dev/null || echo unknown; }
# How full that filesystem is, as a bare integer.
fill_pct() { df --output=pcent "$1" 2>/dev/null | tail -1 | tr -dc '0-9' || echo 0; }

# Guarded rather than trusting the caller: an empty argument would expand to
# `rm -rf /`, and this runs unattended.
drop() {
  local path="$1" why="$2"
  [ -n "$path" ] && [ -d "$path" ] || return 0
  freed=$((freed + $(size_kb "$path")))
  rm -rf "${path:?}"
  note "removed ${path#"${root:-}"/} — $why"
}

prune_once() {
  freed=0

  # --- VS Code server builds -------------------------------------------------
  # Deleting the build in use takes the editor down with it, and mtime cannot
  # identify it: reading a file inside a build updates its timestamp, so "keep
  # the newest" can point at a stale one. `/proc` is the only reliable source.
  builds="$SERVER_BUILDS"
  if [ -d "$builds" ]; then
    in_use="$(
      { cat /proc/[0-9]*/cmdline 2>/dev/null || true; } \
        | tr '\0' '\n' \
        | grep -o "$builds/[a-f0-9]\{40\}" \
        | sort -u || true
    )"
    # Plus the most recent few: at container start the server may not be
    # running yet, leaving the timestamp as the only signal.
    recent="$(find "$builds" -mindepth 1 -maxdepth 1 -type d -printf '%T@ %p\n' 2>/dev/null \
      | sort -rn | head -n "$KEEP_SERVER_BUILDS" | cut -d' ' -f2-)"
  
    for build in "$builds"/*/; do
      build="${build%/}"
      case "$recent" in *"$build"*) continue ;; esac
      case "$in_use" in *"$build"*) continue ;; esac
      freed=$((freed + $(size_kb "$build")))
      rm -rf "$build"
      note "removed stale server build $(basename "$build")"
    done
  fi
  
  # --- Extension download caches ---------------------------------------------
  # Downloaded VSIX files only; the extensions live in their own volume.
  for cache in /vscode/vscode-server/extensionsCache "$HOME/.vscode-server/extensionsCache"; do
    if [ -d "$cache" ]; then
      kb="$(size_kb "$cache")"
      [ "$kb" -gt 51200 ] || continue   # under 50 MB, not worth the churn
      freed=$((freed + kb))
      rm -rf "${cache:?}"/*
      note "cleared $cache"
    fi
  done
  
  # --- Rust build tree -------------------------------------------------------
  # A ceiling, not a wipe: these cost minutes to rebuild, so they are only
  # touched once the tree has grown past what a working checkout needs.
  # `incremental` is regenerated by the next build and `llvm-cov-target` by the
  # next coverage run, which is the least often used of the two.
  #
  # Where the tree lives decides what "too big" means. On disk, growth costs
  # disk. On a tmpfs it costs the build: a full one fails the compile with
  # ENOSPC, which reads as a broken toolchain. So the ramdisk is measured by how
  # full it is, and acted on well before it is.
  target="${CARGO_TARGET_DIR:-${root:+$root/backend/target}}"
  if [ -n "$target" ] && [ -d "$target" ]; then
    if [ "$(fs_of "$target")" = "tmpfs" ]; then
      # Test scratch that outlived its process: the suites write under TMPDIR
      # and a run that is killed leaves its directory behind. An hour old is
      # nothing still running.
      find "$RAMDISK" -mindepth 1 -maxdepth 1 -name 'routarr-*' -mmin +60 -exec rm -rf {} + 2>/dev/null || true
      # 75%: enough headroom left for the `--release` build the e2e harness
      # makes, which is the largest single thing that lands here.
      if [ "$(fill_pct "$target")" -ge 75 ]; then
        for spill in "$target"/*/incremental "$target/llvm-cov-target"; do
          drop "$spill" "ramdisk over 75% full"
        done
        # Re-measured: dropping the cheap caches is usually enough, and
        # `debug` costs minutes to rebuild.
        if [ "$(fill_pct "$target")" -ge 90 ]; then
          drop "$target/debug" "ramdisk still over 90% full after the cheap sweep"
        fi
      fi
    else
      ceiling_kb=$((6 * 1024 * 1024))       # 6 GB
      if [ "$(size_kb "$target")" -gt "$ceiling_kb" ]; then
        for spill in "$target"/*/incremental "$target/llvm-cov-target"; do
          drop "$spill" "over the $((ceiling_kb / 1024 / 1024)) GB ceiling"
        done
      fi
    fi
  fi

  # --- The build tree the ramdisk replaced -----------------------------------
  # With `CARGO_TARGET_DIR` elsewhere, `backend/target` is gigabytes nothing
  # will read again. Three conditions, all required: the root really is this
  # repository, the path is not the tree in use, and it carries the
  # `CACHEDIR.TAG` cargo writes and no source tree has.
  stale="${root:+$root/backend/target}"
  if [ -n "$stale" ] && [ -n "${CARGO_TARGET_DIR:-}" ] && [ -f "$stale/CACHEDIR.TAG" ] \
     && [ "$(readlink -f "$stale")" != "$(readlink -f "$CARGO_TARGET_DIR" 2>/dev/null || echo /nonexistent)" ]; then
    drop "$stale" "superseded by CARGO_TARGET_DIR=$CARGO_TARGET_DIR"
  fi

  # Silent when there is nothing to do: this runs on every attach, and a line
  # per window reload is how a useful message stops being read.
  if [ "$freed" -gt 0 ]; then
    note "reclaimed $((freed / 1024)) MB"
  fi
}

# ---------------------------------------------------------------- scheduling
# `--daemon` prunes inline and arms a loop on top. The hooks are events, not a
# clock: a container left running with no window attaching fires neither again,
# which is when the ramdisk grows. Every pass is appended to LOG.
INTERVAL=1800                       # thirty minutes: one coverage pass adds ~2 GB
LOCK=/tmp/routarr-prune.lock
LOG=/tmp/routarr-prune.log

case "${1:-}" in
  --status)
    # Read-only. The first thing to run when a build reports no space left.
    if [ "$(fs_of "$RAMDISK")" = "tmpfs" ]; then
      df -h "$RAMDISK" | tail -1 | awk '{print "ramdisk: " $2 " total, " $3 " used, " $4 " free (" $5 ")"}'
      du -sh "$RAMDISK"/* 2>/dev/null | sort -rh | head -5 | sed 's/^/  /'
    else
      echo "ramdisk: $RAMDISK is not a tmpfs — see .devcontainer/ramdisk.sh" >&2
    fi
    for keep in /cargo /playwright /vscode "${root:+$root/frontend/node_modules}" "${root:+$root/site/node_modules}"; do
      [ -n "$keep" ] && [ -d "$keep" ] && printf 'kept: %-28s %s\n' "$keep" "$(du -sh "$keep" 2>/dev/null | cut -f1)"
    done
    # /vscode is mostly server builds. A start stalls for minutes when none of
    # them matches the version VS Code has just updated to.
    for build in "$SERVER_BUILDS"/*/; do
      [ -d "$build" ] || continue
      printf '  server build %s  %6s  %s\n' "$(basename "${build%/}" | cut -c1-12)" \
        "$(du -sh "$build" 2>/dev/null | cut -f1)" "$(stat -c %y "$build" | cut -c1-16)"
    done
    ;;
  --loop)
    exec 9>"$LOCK"
    # Already running: leave the incumbent alone and say nothing.
    flock -n 9 || exit 0
    echo "prune: loop armed, every $((INTERVAL / 60)) min, pid $$ — $(date -Is)"
    # Waits first: the caller has just pruned inline, so a pass now would only
    # repeat it.
    while true; do
      # fd 9 closed for the child: an inherited lock outlives this process by a
      # whole interval, and no replacement loop can get past it.
      sleep "$INTERVAL" 9>&-
      echo "--- $(date -Is)"
      prune_once || echo "prune: pass failed, continuing"
    done
    ;;
  --daemon)
    # Inline: an idle pass is milliseconds, and a process detached from a
    # lifecycle hook does not reliably outlive the exec session that spawned it.
    prune_once
    setsid bash "${BASH_SOURCE[0]}" --loop >>"$LOG" 2>&1 < /dev/null &
    # One line, always, even on an idle pass. This runs where VS Code prints
    # "Running the postAttachCommand" and shows nothing else, and a hook that
    # returns without a word is indistinguishable from one that is stuck.
    fill="$(df -h "$RAMDISK" 2>/dev/null | tail -1 | awk '{print $5 " of " $2 " used"}')"
    note "${fill:-ramdisk not measurable}, sweep armed every $((INTERVAL / 60)) min"
    ;;
  *)
    prune_once
    ;;
esac
