import type { CardHelp, ScreenHelp, Term } from './help';

/** Every term the help defines, by id: the word the interface uses and what it means. */
export const TERMS: Readonly<Record<string, Term>> = {
  ApplicationKey: { name: 'SecurityKindApplicationKey', text: 'TermTextApplicationKey' },
  Apply: { name: 'ApplyLabel', text: 'TermTextApply' },
  ArrApiKey: { name: 'TermArrApiKey', text: 'TermTextArrApiKey' },
  AutoApply: { name: 'SettingAutoApply', text: 'TermTextAutoApply' },
  Backup: { name: 'TermBackup', text: 'TermTextBackup' },
  BaseUrl: { name: 'BaseUrl', text: 'TermTextBaseUrl' },
  BatchLimit: { name: 'SettingBatchLimit', text: 'TermTextBatchLimit' },
  CachedEntries: { name: 'CachedEntries', text: 'TermTextCachedEntries' },
  Category: { name: 'Category', text: 'TermTextCategory' },
  CertificationRegions: {
    name: 'SettingCertificationRegions',
    text: 'TermTextCertificationRegions',
  },
  Condition: { name: 'TermCondition', text: 'TermTextCondition' },
  Confidence: { name: 'Confidence', text: 'TermTextConfidence' },
  ConfirmationThreshold: {
    name: 'SettingConfirmationThreshold',
    text: 'TermTextConfirmationThreshold',
  },
  Decision: { name: 'TermDecision', text: 'TermTextDecision' },
  DefaultCategory: { name: 'SettingDefaultCategory', text: 'TermTextDefaultCategory' },
  Destination: { name: 'DeclareDestination', text: 'TermTextDestination' },
  DryRun: { name: 'SettingGlobalDryRun', text: 'TermTextDryRun' },
  Enrichment: { name: 'TermEnrichment', text: 'TermTextEnrichment' },
  Exception: { name: 'TermException', text: 'TermTextException' },
  Exclusion: { name: 'TermExclusion', text: 'TermTextExclusion' },
  FailedDecisions: { name: 'FailedDecisions', text: 'TermTextFailedDecisions' },
  FolderMapping: { name: 'TermFolderMapping', text: 'TermTextFolderMapping' },
  Guardrails: { name: 'SettingsTabGuardrails', text: 'TermTextGuardrails' },
  Inaccessible: { name: 'Inaccessible', text: 'TermTextInaccessible' },
  InactiveSource: { name: 'TermInactiveSource', text: 'TermTextInactiveSource' },
  Instance: { name: 'Instance', text: 'TermTextInstance' },
  InstanceEnabled: { name: 'EnabledSyncedRouted', text: 'TermTextInstanceEnabled' },
  LastSync: { name: 'LastSync', text: 'TermTextLastSync' },
  Maintenance: { name: 'JobMaintenance', text: 'TermTextMaintenance' },
  MappedFolders: { name: 'MappedFolders', text: 'TermTextMappedFolders' },
  MayConfirm: { name: 'ApplicationMayConfirm', text: 'TermTextMayConfirm' },
  MetadataCache: { name: 'TermMetadataCache', text: 'TermTextMetadataCache' },
  MetadataSource: { name: 'TermMetadataSource', text: 'TermTextMetadataSource' },
  MissingMetadata: { name: 'MissingMetadata', text: 'TermTextMissingMetadata' },
  Move: { name: 'ActionMove', text: 'TermTextMove' },
  MoveFiles: { name: 'ApplicationMayMoveFiles', text: 'TermTextMoveFiles' },
  MoveLog: { name: 'Logs', text: 'TermTextMoveLog' },
  NoKey: { name: 'TermNoKey', text: 'TermTextNoKey' },
  Operation: { name: 'TermOperation', text: 'TermTextOperation' },
  OtherSite: { name: 'SecurityKindOrigin', text: 'TermTextOtherSite' },
  Outcome: { name: 'Outcome', text: 'TermTextOutcome' },
  PerformedBy: { name: 'PerformedBy', text: 'TermTextPerformedBy' },
  Priority: { name: 'Priority', text: 'TermTextPriority' },
  Proof: { name: 'SecurityKindProof', text: 'TermTextProof' },
  ProposedCategory: { name: 'ProposedCategory', text: 'TermTextProposedCategory' },
  Refused: { name: 'SecurityOutcomeRefused', text: 'TermTextRefused' },
  Repeated: { name: 'TermRepeated', text: 'TermTextRepeated' },
  Requested: { name: 'StatusRequested', text: 'TermTextRequested' },
  Revert: { name: 'Revert', text: 'TermTextRevert' },
  RootFolder: { name: 'TermRootFolder', text: 'TermTextRootFolder' },
  RoutarrApiKey: { name: 'RoutarrApiKey', text: 'TermTextRoutarrApiKey' },
  Rule: { name: 'Rule', text: 'TermTextRule' },
  RuleScope: { name: 'TermRuleScope', text: 'TermTextRuleScope' },
  RuleTest: { name: 'TermRuleTest', text: 'TermTextRuleTest' },
  Scheduler: { name: 'JobScheduler', text: 'TermTextScheduler' },
  Schema: { name: 'TermSchema', text: 'TermTextSchema' },
  Scope: { name: 'TermKeyScope', text: 'TermTextScope' },
  ScopeConfigure: { name: 'TermScopeConfigure', text: 'TermTextScopeConfigure' },
  ScopeOperate: { name: 'TermScopeOperate', text: 'TermTextScopeOperate' },
  ScopeRead: { name: 'TermScopeRead', text: 'TermTextScopeRead' },
  ScopeWrite: { name: 'TermScopeWrite', text: 'TermTextScopeWrite' },
  SecurityEvent: { name: 'TermSecurityEvent', text: 'TermTextSecurityEvent' },
  Simulation: { name: 'Simulation', text: 'TermTextSimulation' },
  SourceApiKey: { name: 'TermSourceApiKey', text: 'TermTextSourceApiKey' },
  SourcePriority: { name: 'TermSourcePriority', text: 'TermTextSourcePriority' },
  Superseded: { name: 'TermSuperseded', text: 'TermTextSuperseded' },
  Sync: { name: 'JobSync', text: 'TermTextSync' },
  Task: { name: 'Task', text: 'TermTextTask' },
  Trigger: { name: 'Trigger', text: 'TermTextTrigger' },
  Webhook: { name: 'TriggerWebhook', text: 'TermTextWebhook' },
  WebhookToken: { name: 'TermWebhookToken', text: 'TermTextWebhookToken' },
};

/** The help of each screen, by its address, in the order of the navigation. */
export const HELP: Readonly<Record<string, ScreenHelp>> = {
  '/': {
    purpose: 'HelpPurposeDashboard',
    terms: ['Decision', 'Simulation', 'Instance', 'Sync', 'RootFolder', 'MetadataSource', 'DryRun'],
    problems: [
      { problem: 'HelpProblemDashboard1', fix: 'HelpFixDashboard1', to: '/instances' },
      { problem: 'HelpProblemDashboard2', fix: 'HelpFixDashboard2', to: '/diagnostics' },
      { problem: 'HelpProblemDashboard3', fix: 'HelpFixDashboard3', to: '/move-log' },
      { problem: 'HelpProblemDashboard4', fix: 'HelpFixDashboard4', to: '/sources' },
    ],
    cards: ['DashboardInstances', 'GuideTitle'],
  },
  '/rules': {
    purpose: 'HelpPurposeRulesEngine',
    terms: [
      'Rule',
      'Priority',
      'Condition',
      'Exclusion',
      'RuleScope',
      'Category',
      'DefaultCategory',
    ],
    problems: [
      { problem: 'HelpProblemRulesEngine1', fix: 'HelpFixRulesEngine1' },
      { problem: 'HelpProblemRulesEngine2', fix: 'HelpFixRulesEngine2' },
      { problem: 'HelpProblemRulesEngine3', fix: 'HelpFixRulesEngine3', to: '/categories' },
      { problem: 'HelpProblemRulesEngine4', fix: 'HelpFixRulesEngine4', to: '/sources' },
    ],
    cards: ['LibraryFacets', 'PreviewTitle'],
  },
  '/exceptions': {
    purpose: 'HelpPurposeOverrides',
    terms: ['Exception', 'Category', 'Rule', 'Priority', 'RootFolder', 'Simulation'],
    problems: [
      { problem: 'HelpProblemOverrides1', fix: 'HelpFixOverrides1', to: '/simulation' },
      { problem: 'HelpProblemOverrides2', fix: 'HelpFixOverrides2', to: '/instances' },
      { problem: 'HelpProblemOverrides3', fix: 'HelpFixOverrides3', to: '/categories' },
      { problem: 'HelpProblemOverrides4', fix: 'HelpFixOverrides4' },
    ],
    cards: [],
  },
  '/rule-tests': {
    purpose: 'HelpPurposeRuleTests',
    terms: ['RuleTest', 'Rule', 'Priority', 'Category', 'Exception', 'DefaultCategory'],
    problems: [
      { problem: 'HelpProblemRuleTests1', fix: 'HelpFixRuleTests1', to: '/library' },
      { problem: 'HelpProblemRuleTests2', fix: 'HelpFixRuleTests2', to: '/rules' },
      { problem: 'HelpProblemRuleTests3', fix: 'HelpFixRuleTests3', to: '/library' },
    ],
    cards: [],
  },
  '/simulation': {
    purpose: 'HelpPurposeSimulation',
    terms: [
      'Simulation',
      'Decision',
      'Apply',
      'Guardrails',
      'DryRun',
      'Confidence',
      'Exception',
      'DefaultCategory',
    ],
    problems: [
      { problem: 'HelpProblemSimulation1', fix: 'HelpFixSimulation1', to: '/settings' },
      { problem: 'HelpProblemSimulation2', fix: 'HelpFixSimulation2' },
      { problem: 'HelpProblemSimulation3', fix: 'HelpFixSimulation3', to: '/categories' },
      { problem: 'HelpProblemSimulation4', fix: 'HelpFixSimulation4' },
    ],
    cards: ['CapacityTitle'],
  },
  '/library': {
    purpose: 'HelpPurposeMediaExplorer',
    terms: [
      'ProposedCategory',
      'Instance',
      'RootFolder',
      'Sync',
      'MetadataSource',
      'Exception',
      'RuleTest',
      'Confidence',
    ],
    problems: [
      { problem: 'HelpProblemMediaExplorer1', fix: 'HelpFixMediaExplorer1', to: '/instances' },
      { problem: 'HelpProblemMediaExplorer2', fix: 'HelpFixMediaExplorer2', to: '/simulation' },
      { problem: 'HelpProblemMediaExplorer3', fix: 'HelpFixMediaExplorer3' },
      { problem: 'HelpProblemMediaExplorer4', fix: 'HelpFixMediaExplorer4', to: '/simulation' },
    ],
    cards: ['MetadataTitle', 'RuleEvaluation'],
  },
  '/history': {
    purpose: 'HelpPurposeAuditHistory',
    terms: [
      'Decision',
      'Superseded',
      'Requested',
      'RootFolder',
      'Confidence',
      'DefaultCategory',
      'Exception',
      'Revert',
    ],
    problems: [
      { problem: 'HelpProblemAuditHistory1', fix: 'HelpFixAuditHistory1', to: '/library' },
      { problem: 'HelpProblemAuditHistory2', fix: 'HelpFixAuditHistory2', to: '/simulation' },
      { problem: 'HelpProblemAuditHistory3', fix: 'HelpFixAuditHistory3' },
      { problem: 'HelpProblemAuditHistory4', fix: 'HelpFixAuditHistory4', to: '/settings' },
    ],
    cards: [],
  },
  '/tasks': {
    purpose: 'HelpPurposeTasks',
    terms: [
      'Task',
      'Trigger',
      'Sync',
      'Enrichment',
      'Simulation',
      'Apply',
      'Maintenance',
      'Scheduler',
    ],
    problems: [
      { problem: 'HelpProblemTasks1', fix: 'HelpFixTasks1', to: '/instances' },
      { problem: 'HelpProblemTasks2', fix: 'HelpFixTasks2', to: '/instances' },
      { problem: 'HelpProblemTasks3', fix: 'HelpFixTasks3', to: '/move-log' },
      { problem: 'HelpProblemTasks4', fix: 'HelpFixTasks4', to: '/simulation' },
    ],
    cards: [],
  },
  '/move-log': {
    purpose: 'HelpPurposeLogs',
    terms: ['MoveLog', 'Move', 'Revert', 'Trigger', 'PerformedBy', 'Outcome'],
    problems: [
      { problem: 'HelpProblemLogs1', fix: 'HelpFixLogs1', to: '/settings' },
      { problem: 'HelpProblemLogs2', fix: 'HelpFixLogs2', to: '/instances' },
      { problem: 'HelpProblemLogs3', fix: 'HelpFixLogs3', to: '/history' },
      { problem: 'HelpProblemLogs4', fix: 'HelpFixLogs4', to: '/settings' },
    ],
    cards: [],
  },
  '/security-log': {
    purpose: 'HelpPurposeSecurityLog',
    terms: [
      'SecurityEvent',
      'Refused',
      'RoutarrApiKey',
      'ApplicationKey',
      'Scope',
      'OtherSite',
      'Proof',
      'Repeated',
    ],
    problems: [
      { problem: 'HelpProblemSecurityLog1', fix: 'HelpFixSecurityLog1' },
      { problem: 'HelpProblemSecurityLog2', fix: 'HelpFixSecurityLog2' },
      { problem: 'HelpProblemSecurityLog3', fix: 'HelpFixSecurityLog3', to: '/applications' },
      { problem: 'HelpProblemSecurityLog4', fix: 'HelpFixSecurityLog4', to: '/applications' },
    ],
    cards: [],
  },
  '/diagnostics': {
    purpose: 'HelpPurposeDiagnostics',
    terms: [
      'Instance',
      'LastSync',
      'MappedFolders',
      'MetadataSource',
      'MissingMetadata',
      'CachedEntries',
      'FailedDecisions',
    ],
    problems: [
      { problem: 'HelpProblemDiagnostics1', fix: 'HelpFixDiagnostics1', to: '/instances' },
      { problem: 'HelpProblemDiagnostics2', fix: 'HelpFixDiagnostics2', to: '/categories' },
      { problem: 'HelpProblemDiagnostics3', fix: 'HelpFixDiagnostics3', to: '/sources' },
      { problem: 'HelpProblemDiagnostics4', fix: 'HelpFixDiagnostics4', to: '/tasks' },
    ],
    cards: ['ArrInstances', 'HealthMetadataSources'],
  },
  '/instances': {
    purpose: 'HelpPurposeInstances',
    terms: [
      'Instance',
      'Sync',
      'BaseUrl',
      'ArrApiKey',
      'InstanceEnabled',
      'Webhook',
      'WebhookToken',
    ],
    problems: [
      { problem: 'HelpProblemInstances1', fix: 'HelpFixInstances1' },
      { problem: 'HelpProblemInstances2', fix: 'HelpFixInstances2' },
      { problem: 'HelpProblemInstances3', fix: 'HelpFixInstances3' },
      { problem: 'HelpProblemInstances4', fix: 'HelpFixInstances4' },
    ],
    cards: [],
  },
  '/categories': {
    purpose: 'HelpPurposeRootFolders',
    terms: [
      'Category',
      'RootFolder',
      'FolderMapping',
      'Destination',
      'DefaultCategory',
      'Inaccessible',
    ],
    problems: [
      { problem: 'HelpProblemRootFolders1', fix: 'HelpFixRootFolders1', to: '/instances' },
      { problem: 'HelpProblemRootFolders2', fix: 'HelpFixRootFolders2' },
      { problem: 'HelpProblemRootFolders3', fix: 'HelpFixRootFolders3', to: '/instances' },
      { problem: 'HelpProblemRootFolders4', fix: 'HelpFixRootFolders4' },
    ],
    cards: ['FolderMappings', 'Categories'],
  },
  '/sources': {
    purpose: 'HelpPurposeMetadataSources',
    terms: [
      'MetadataSource',
      'SourcePriority',
      'InactiveSource',
      'SourceApiKey',
      'CertificationRegions',
      'MetadataCache',
    ],
    problems: [
      { problem: 'HelpProblemMetadataSources1', fix: 'HelpFixMetadataSources1' },
      { problem: 'HelpProblemMetadataSources2', fix: 'HelpFixMetadataSources2' },
      { problem: 'HelpProblemMetadataSources3', fix: 'HelpFixMetadataSources3' },
      { problem: 'HelpProblemMetadataSources4', fix: 'HelpFixMetadataSources4' },
    ],
    cards: [
      'SettingsMetadataSources',
      'SettingsMetadataCoverage',
      'SourceRefreshTitle',
      'SourceCreditsTitle',
    ],
  },
  '/settings': {
    purpose: 'HelpPurposeSettings',
    terms: [
      'DryRun',
      'Guardrails',
      'BatchLimit',
      'ConfirmationThreshold',
      'DefaultCategory',
      'AutoApply',
      'RoutarrApiKey',
      'Backup',
    ],
    problems: [
      { problem: 'HelpProblemSettings1', fix: 'HelpFixSettings1' },
      { problem: 'HelpProblemSettings2', fix: 'HelpFixSettings2' },
      { problem: 'HelpProblemSettings3', fix: 'HelpFixSettings3' },
      { problem: 'HelpProblemSettings4', fix: 'HelpFixSettings4', to: '/instances' },
    ],
    cards: [
      'GuideRestart',
      'SettingsTabGeneral',
      'RoutarrApiKey',
      'Account',
      'Sessions',
      'SettingsTabSecurity',
      'SettingsTabGuardrails',
      'SettingsTabAutomation',
      'SettingsTabNotifications',
      'NotificationTest',
      'WebhookSigning',
      'BackupEncryption',
      'Backups',
      'SettingsTabMaintenance',
    ],
  },
  '/applications': {
    purpose: 'HelpPurposeApplications',
    terms: [
      'ApplicationKey',
      'Scope',
      'ScopeRead',
      'ScopeOperate',
      'ScopeWrite',
      'ScopeConfigure',
      'MayConfirm',
      'MoveFiles',
    ],
    problems: [
      { problem: 'HelpProblemApplications1', fix: 'HelpFixApplications1' },
      { problem: 'HelpProblemApplications2', fix: 'HelpFixApplications2' },
      { problem: 'HelpProblemApplications3', fix: 'HelpFixApplications3' },
      { problem: 'HelpProblemApplications4', fix: 'HelpFixApplications4', to: '/simulation' },
    ],
    cards: [],
  },
  '/reference': {
    purpose: 'HelpPurposeApiReference',
    terms: ['ApplicationKey', 'Scope', 'Operation', 'NoKey', 'Schema', 'Guardrails', 'Task'],
    problems: [
      { problem: 'HelpProblemApiReference1', fix: 'HelpFixApiReference1', to: '/applications' },
      { problem: 'HelpProblemApiReference2', fix: 'HelpFixApiReference2', to: '/applications' },
      { problem: 'HelpProblemApiReference3', fix: 'HelpFixApiReference3', to: '/applications' },
      { problem: 'HelpProblemApiReference4', fix: 'HelpFixApiReference4' },
    ],
    cards: [
      'ApiTagStatus',
      'ApiTagLibrary',
      'ApiTagDecisions',
      'ApiTagExceptions',
      'ApiTagTasks',
      'ApiTagInstances',
      'ApiTagRules',
      'ApiTagCategories',
      'ApiTagBackups',
      'ApiSchemas',
    ],
  },
};

/** What each card's "?" says, by the id its title is drawn with. */
export const CARD_HELP: Readonly<Record<string, CardHelp>> = {
  Account: { title: 'Account', text: 'HelpCardAccount' },
  ApiSchemas: { title: 'ApiSchemas', text: 'HelpCardApiSchemas' },
  ApiTagBackups: { title: 'ApiTagBackups', text: 'HelpCardApiTagBackups' },
  ApiTagCategories: { title: 'ApiTagCategories', text: 'HelpCardApiTagCategories' },
  ApiTagDecisions: { title: 'ApiTagDecisions', text: 'HelpCardApiTagDecisions' },
  ApiTagExceptions: { title: 'ApiTagExceptions', text: 'HelpCardApiTagExceptions' },
  ApiTagInstances: { title: 'ApiTagInstances', text: 'HelpCardApiTagInstances' },
  ApiTagLibrary: { title: 'ApiTagLibrary', text: 'HelpCardApiTagLibrary' },
  ApiTagRules: { title: 'ApiTagRules', text: 'HelpCardApiTagRules' },
  ApiTagStatus: { title: 'ApiTagStatus', text: 'HelpCardApiTagStatus' },
  ApiTagTasks: { title: 'ApiTagTasks', text: 'HelpCardApiTagTasks' },
  ArrInstances: { title: 'ArrInstances', text: 'HelpCardArrInstances' },
  BackupEncryption: { title: 'BackupEncryption', text: 'HelpCardBackupEncryption' },
  Backups: { title: 'Backups', text: 'HelpCardBackups' },
  CapacityTitle: { title: 'CapacityTitle', text: 'HelpCardCapacityTitle' },
  Categories: { title: 'Categories', text: 'HelpCardCategories' },
  DashboardInstances: { title: 'Instances', text: 'HelpCardDashboardInstances' },
  FolderMappings: { title: 'FolderMappings', text: 'HelpCardFolderMappings' },
  GuideRestart: { title: 'GuideTitle', text: 'HelpCardGuideRestart' },
  GuideTitle: { title: 'GuideTitle', text: 'HelpCardGuideTitle' },
  HealthMetadataSources: {
    title: 'SettingMetadataProviders',
    text: 'HelpCardHealthMetadataSources',
  },
  LibraryFacets: { title: 'LibraryFacetsTitle', text: 'HelpCardLibraryFacets' },
  MetadataTitle: { title: 'MetadataTitle', text: 'HelpCardMetadataTitle' },
  NotificationTest: { title: 'NotificationTest', text: 'HelpCardNotificationTest' },
  PreviewTitle: { title: 'PreviewTitle', text: 'HelpCardPreviewTitle' },
  RoutarrApiKey: { title: 'RoutarrApiKey', text: 'HelpCardRoutarrApiKey' },
  RuleEvaluation: { title: 'RuleEvaluation', text: 'HelpCardRuleEvaluation' },
  Sessions: { title: 'Sessions', text: 'HelpCardSessions' },
  SettingsMetadataCoverage: {
    title: 'SettingsMetadataCoverage',
    text: 'HelpCardSettingsMetadataCoverage',
  },
  SettingsMetadataSources: {
    title: 'SettingMetadataProviders',
    text: 'HelpCardSettingsMetadataSources',
  },
  SettingsTabAutomation: { title: 'SettingsTabAutomation', text: 'HelpCardSettingsTabAutomation' },
  SettingsTabGeneral: { title: 'SettingsTabGeneral', text: 'HelpCardSettingsTabGeneral' },
  SettingsTabGuardrails: { title: 'SettingsTabGuardrails', text: 'HelpCardSettingsTabGuardrails' },
  SettingsTabMaintenance: {
    title: 'SettingsTabMaintenance',
    text: 'HelpCardSettingsTabMaintenance',
  },
  SettingsTabNotifications: {
    title: 'SettingsTabNotifications',
    text: 'HelpCardSettingsTabNotifications',
  },
  SettingsTabSecurity: { title: 'SettingsTabSecurity', text: 'HelpCardSettingsTabSecurity' },
  SourceCreditsTitle: { title: 'SourceCreditsTitle', text: 'HelpCardSourceCreditsTitle' },
  SourceRefreshTitle: { title: 'SourceRefreshTitle', text: 'HelpCardSourceRefreshTitle' },
  WebhookSigning: { title: 'WebhookSigning', text: 'HelpCardWebhookSigning' },
};
